title: Developer Platform
description: API Documentation for Maker Developers

highlighter: rouge
markdown: kramdown

dai-tub: 0xf24888d405776cc56d29e70448172380708bb7a5
dai-top: 0xf24888d405776cc56d29e70448172380708bb7a5

apiRoot: https://api.oasisdex.com/rest/v1
